[hotkeys]
menuhotkey="!c"
exithotkey="+!c"

[timing]
hintTimeShort=1500
hintTimeMedium=2000
hintTime=3000
hintTimeLong=20000

[config]
font="Segoe UI"
fontsize=9
sessionfiles="C:\___jvr_work\npp-sessions\"
sessionfileExtension=".npp-session"

[external]
notepadppPath="C:\Program Files\Notepad++\notepad++.exe"
runnerPath=C:\___x2_wrk\_autohotkey\lang2\winHttpRequest_test.ahk

[fastSwitchCycle]
fastSwitchCycleGroupSelected=1
fastSwitchCycleHotkey=""

;fastSwitchCycleGroup1 is fixed to "Off"
fastSwitchCycleGroup2_Off="!d,!n"
fastSwitchCycleGroup3_Off="!d,!n,!b"
fastSwitchCycleGroup4_Off="!b,!k"
fastSwitchCycleGroup5_Off="!n,!b"
fastSwitchCycleGroup6_Off="!n,!f"
fastSwitchCycleGroup7_Off="!n,!k"
fastSwitchCycleGroup8_Off="!n,!k,!d"
fastSwitchCycleGroup9_Off="!d,!o"

fastSwitchAutoCycleHotkey="!q"

fastSwitchUseTitle="ConsoleWindowClass"

[openSessionTiming]
waitForNotepadReady=500
waitForSessionManagerLoop=500
waitForEditReady=500
waitDokListOpenLoop=500

[gui]
dpiScale=96
windowPosX=0
windowPosY=0
clientWidth=1412
clientHeight=713
currentSelected=14
